name: Docs deploy

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'website/**'
      - 'README.md'
      - '.github/workflows/docs-deploy.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci
          cd website && npm install && cd -
      - name: Build documentation
        run: cd website && npm run build && cd -
      - name: Build API documentation
        run: npm run docs:api
      - name: Zip docs
        run: |
          mv docs website/build/docs/api
          cd website/build
          zip -r docs.zip .
      - name: Copy docs to Toolforge
        uses: garygrossgarten/github-action-scp@dba89d858413133b6e35da91a3c989cc8cde3ad4
        with:
          local: ${{github.workspace}}/website/build/docs.zip
          remote: /var/www/html/docs.zip
          host: 13.233.17.5
          username: ${{secrets.TOOLFORGE_USERNAME}}
          privateKey: ${{secrets.TOOLFORGE_PRIVATE_KEY}}
          rmRemote: true
      - name: Unzip
        uses: garygrossgarten/github-action-ssh@2b10f41b5a33808f6d24eafd253296766308b7c4
        with:
          command: |
            cd /data/project/mwn/www/static
            shopt -s extglob
            rm -r -- !(coverage)
            unzip /data/project/mwn/docs.zip -d .
            rm /data/project/mwn/docs.zip
          host: 13.233.17.5
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.PRIVATE_KEY}}
